// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package builder

import (
	"database/sql"
	wire2 "github.com/google/wire"
	"github.com/smartlog/api/tools/wire"
)

// Injectors from api.go:

func Initialize() (*ApiService, func(), error) {
	db, cleanup, err := wire.NewClickHouse()
	if err != nil {
		return nil, nil, err
	}
	apiService := NewApiService(db)
	return apiService, func() {
		cleanup()
	}, nil
}

// api.go:

var ApiSet = wire2.NewSet(wire.NewClickHouse, NewApiService)

type ApiService struct {
	ClickHouse *sql.DB
}

func NewApiService(clickhouse *sql.DB) *ApiService {
	return &ApiService{
		ClickHouse: clickhouse,
	}
}
